### PR TITLE
Remove classNames and style feature, out of package's scope

### PR DESCRIPTION
**Pull request by petejodo**

### CODE REVIEW

**Comment by petejodo** [comment]
@twhid 

you seem to be the only one I can refer to. Tried adding @hellatan. Also I can't set assignees.

I just removed the entire feature of `style` and `className` from `react-portal` since it's not something this package should be concerned with (it should just render something somewhere else, no styling required). This won't affect `react-modal`wrapper`since that handles applying`className`, etc

**edit:** Oh looks like it worked for hellatan

**edit:** I already tested this with `react-modal-wrapper` without issue

**Comment by twhid** [comment]
Added @1stdibs/code-monkeys. You should be able to assign, etc.

**Comment by twhid** [comment]
We shouldn't be replacing that functionality with something else?

**Comment by petejodo** [comment]
I feel it's unnecessary to have styling in a functional component since users can just have another `div` with the necessary styling/class that wraps their content. I could just replace that functionality with something else.

Note, it looks like the collaborators for react-portal came up with the same solution https://github.com/tajo/react-portal/pull/105

**Comment by twhid** [comment]
LGTM

**Comment by twhid** [comment]
We'll need to rename it before we publish it.

**Review by twhid — CHANGES_REQUESTED** [review]
Rename the package.

**Comment by petejodo** [comment]
oh I just noticed I missed the `shallowCompare` which is still coming from `react/libs`. I didn't catch it cause it looks like it's still react. I should remove that now before we run into this situation again

**Comment by petejodo** [comment]
@twhid could we just publish under a namespace i.e. @1stdibs/react-portal?

**Comment by twhid** [comment]
We haven't been publishing under namespaces, but we could give it a shot.

**Review by twhid — APPROVED** [review]

**Comment by petejodo** [comment]
Added package scope, might have to be published like `npm publish --access=public`

More details here https://docs.npmjs.com/getting-started/scoped-packages

**Comment by twhid** [comment]
I'll publish it.

**Comment by twhid** [comment]
https://www.npmjs.com/package/@1stdibs/react-portal

**Comment by petejodo** [comment]
will update `react-modal-wrapper` with this new package

**Pull request merged**
