### PR TITLE
changed React.PropTypes -> PropTypes

### PR DESCRIPTION
**Pull request by hellatan**
ran this codemod: https://github.com/reactjs/react-codemod/blob/master/transforms/React-PropTypes-to-prop-types.js to the entire `./lib` dir

### CODE REVIEW

**Comment by hellatan** [comment]
we're using this sparingly now but it's still being used nonetheless 😞

**Comment by petejodo** [comment]
still?! ugh 😞 
just die already react-portal/react-modal-wrapper

**Review by petejodo — APPROVED** [review]

**Comment by hellatan** [comment]
some legacy modal in .com

**Comment by hellatan** [comment]
weird...this didn't fail even though `prop-types` is not in package.json. I'm updating just so that it doesn't fail further down the line.

**Pull request merged**
